"""
aligner.py
Faster-Whisper word-level timestamp extractor for Timestamp Script Analyzer.

Responsibilities:
- Load the Faster-Whisper base model (CPU, int8)
- Transcribe the generated audio file with word_timestamps=True
- Return a flat list of word objects: [{ word, start, end }, ...]

These timestamps come from the real audio — never estimated.
"""

import os
from typing import List, Dict

# Lazy-load the model to avoid slow import at startup
_model = None


def _get_model():
    """Return a cached WhisperModel instance."""
    global _model
    if _model is None:
        from faster_whisper import WhisperModel
        # 'base' is fast and accurate for clean TTS audio
        # int8 compute type keeps memory low on CPU
        _model = WhisperModel("base", device="cpu", compute_type="int8")
    return _model


def get_word_timestamps(audio_path: str) -> List[Dict]:
    """
    Transcribe audio and return word-level timestamps.

    Args:
        audio_path: Absolute path to the WAV file generated by Kokoro TTS.

    Returns:
        List of dicts: [{ "word": str, "start": float, "end": float }, ...]
        Times are in seconds, sourced from the real audio.

    Raises:
        FileNotFoundError: If the audio file does not exist.
        RuntimeError: If Whisper transcription fails.
    """
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    model = _get_model()

    words = []
    try:
        segments, _ = model.transcribe(
            audio_path,
            word_timestamps=True,
            beam_size=5,
            language="en",          # Force English to avoid language detection overhead
            condition_on_previous_text=False  # More accurate for short TTS clips
        )

        for segment in segments:
            if segment.words:
                for word in segment.words:
                    text = word.word.strip()
                    if text:  # Skip empty tokens
                        words.append({
                            "word": text,
                            "start": round(word.start, 4),
                            "end": round(word.end, 4),
                        })
    except Exception as e:
        raise RuntimeError(f"Whisper alignment failed: {e}") from e

    if not words:
        raise RuntimeError("Whisper returned no words. Check the audio file.")

    return words
